### ISSUE TITLE
Enhancement Requests

### ISSUE THREAD

**Issue by charlesfro** [mepatterson/chaosmage-issues#2]
- Slide out with commands as well as character info
- Multiple Portrait sizes (i.e. ability to have different cropped versions for thumbnail vs character sheet, etc)
![image](https://user-images.githubusercontent.com/30133854/87368279-3c1d6580-c54b-11ea-84d5-1f765e4ad0f2.png)
-customized fields with ability to add rolls with tags (e.g. d20+STR+Proficiency)
-ability to hover over past rolls to see actual rolls
-"Play" displays the # players and # of characters, but "Campaigns" still says 0 players
-

**Comment by mepatterson** [comment]
"0 players" has been fixed

**Comment by mepatterson** [comment]
closing this. i've moved these into my roadmap internally
