### ISSUE TITLE
Shortcuts for updating HP & temp HP

### ISSUE THREAD

**Issue by cruinh** [mepatterson/chaosmage-issues#3]
### Description
If you're going to track some basic character stats that might change during battle, it'd be helpful not to have to dive into the character editor to do so.  

### Suggestions
Could be a little UI widget
or could be chat commands?

### Possible Examples 

if my character is "Elliot" and he currently has 28 HP and 28 max HP
- `/damage me 4` => `Elliot now has 24 HP.  `

if my character is "Elliot" and he currently has 28 HP and 4 Temporary HP
- `/damage me 2` => `Elliot now has 28 HP and 2 Temp HP.  `

if my character is "Elliot" and he currently has 20 HP and 28 max HP
- `/heal me 30` => `Elliot now has 28 HP.`

if my character is "Elliot" and he currently has 20 HP
- `/temphp me 4` => `Elliot now has 20 HP and 4 Temp HP.  `

**Comment by mepatterson** [comment]
closing as i've moved this into the internal roadmap
